In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:

- 2*A
- 2+A
- A+B
- A-B
- determinan A
- invers dari B, simpan jadi matriks D
- transpose D
- nilai eigen dan vektor eigen dari A dan B

In [3]:
print(2*A)

[[ 2  4]
 [14 16]]


In [4]:
print(2 + A)

[[ 3  4]
 [ 9 10]]


In [5]:
print(A+B)

[[ 4  7]
 [ 8 14]]


In [6]:
print(A-B)

[[-2 -3]
 [ 6  2]]


In [7]:
D = np.linalg.inv(B)

In [8]:
print(D.transpose())

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


In [9]:
eig_val, eign_vec= np.linalg.eig(A)

In [10]:
print('Eigen Value A = \n',eig_val)

Eigen Value A = 
 [-0.62347538  9.62347538]


In [11]:
print('Eigen Vector A = \n',
      eign_vec)

Eigen Vector A = 
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [13]:
print('Eigen Value B = \n',eig_val)

Eigen Value B = 
 [-0.62347538  9.62347538]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [14]:
print("perkalian antar entry di B dan D = \n",B*D)

perkalian antar entry di B dan D = 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [15]:
print("perkalian matriks B dan D = \n",np.matmul(B,D))

perkalian matriks B dan D = 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
